---
database:
  host: localhost
  user: camunda
  name: workflow
  password: camunda
  port: 5431
  ssl_mode: disable
  batchSize: 100
kassette-server:
  url: http://localhost:8088
  batchSize: 10
kassette-agent:
  customerName: Camunda_Customer
  secretKey: peyj5ssT3K4R6FrvdjS1692375772027
