---
database:
  host: host.docker.internal
  user: camunda
  name: workflow
  password: camunda
  port: 5431
  ssl_mode: disable
  batchSize: 100
kassette-server:
  url: http://host.docker.internal:8088
  batchSize: 10
kassette-agent:
  uid: camunda
